# Generated by Django 4.1.7 on 2023-03-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_tech_fuel_cost'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='power_plant',
        ),
        migrations.RemoveField(
            model_name='generation_system',
            name='power_plant',
        ),
        migrations.CreateModel(
            name='default_generation_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tech')),
            ],
        ),
    ]
