# Generated by Django 4.1.7 on 2023-03-13 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_remove_construction_power_plant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation_system',
            name='username',
            field=models.ForeignKey(db_column='username', default='test', on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
