# Generated by Django 4.1.7 on 2023-03-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_generation_system_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation_system',
            name='username',
        ),
    ]
