# Generated by Django 4.1.7 on 2023-03-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_tech_technology'),
        ('users', '0008_alter_construction_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='construction_time',
        ),
        migrations.RemoveField(
            model_name='generation_system',
            name='operation_time',
        ),
        migrations.AlterField(
            model_name='default_generation_system',
            name='technology',
            field=models.ForeignKey(db_column='technology', on_delete=django.db.models.deletion.CASCADE, to='game.tech', to_field='technology'),
        ),
    ]
