# Generated by Django 4.1.7 on 2023-03-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_construction_construction_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation_system',
            name='username',
        ),
    ]
