# Generated by Django 4.1.7 on 2023-03-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_default_generation_system_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='remaining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generation_system',
            name='remaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
