# Generated by Django 4.1.7 on 2023-03-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_construction_remaining_generation_system_remaining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='construction',
            old_name='remaining',
            new_name='until_constructed',
        ),
        migrations.RenameField(
            model_name='generation_system',
            old_name='remaining',
            new_name='until_decommissioned',
        ),
    ]
