# Generated by Django 4.2.4 on 2023-10-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_tech_default_amount'),
        ('users', '0017_alter_profile_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation_system',
            name='capacity',
            field=models.ManyToManyField(related_name='generation_capacity_set', to='game.tech'),
        ),
    ]
