# Generated by Django 4.2.4 on 2023-10-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_generation_system_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation_system',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
