# Generated by Django 4.2.4 on 2023-10-06 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_tech_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0022_generation_system_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('technology', models.ForeignKey(db_column='technology', on_delete=django.db.models.deletion.CASCADE, to='game.tech', to_field='technology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
