# Generated by Django 4.2.4 on 2023-10-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_rename_games_sessions'),
        ('users', '0023_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joined_game',
            field=models.ForeignKey(blank=True, db_column='name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.sessions', to_field='name'),
        ),
    ]
