# Generated by Django 4.2.4 on 2023-11-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_bids_meritorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='bids',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
