# Generated by Django 4.2.4 on 2023-11-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_alter_settings_value'),
        ('users', '0029_alter_profile_budget_alter_profile_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.sessions', to_field='name')),
            ],
        ),
    ]
