# Generated by Django 4.2.4 on 2023-11-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_backup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='backup',
        ),
    ]
