# Generated by Django 4.1.7 on 2023-03-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('investment_cost', models.IntegerField()),
                ('build_time', models.IntegerField()),
                ('operation_time', models.PositiveIntegerField()),
            ],
        ),
    ]
