# Generated by Django 4.1.7 on 2023-03-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_tech_carbon_content_alter_tech_fuel_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='carbon_content',
            field=models.FloatField(),
        ),
    ]
