# Generated by Django 4.1.7 on 2023-03-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_tech_fuel_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='technology',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
