# Generated by Django 4.2.4 on 2023-10-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_settings_game_alter_settings_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settings',
            unique_together=set(),
        ),
    ]
