# Generated by Django 4.2.4 on 2023-10-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_settings_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='demand_cf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.IntegerField()),
                ('cf_wind', models.IntegerField()),
                ('cf_pv', models.IntegerField()),
                ('round', models.IntegerField()),
            ],
        ),
    ]
