# Generated by Django 4.2.4 on 2023-10-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_demand_cf_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand_cf',
            name='key',
            field=models.CharField(default='game_variables', max_length=30),
        ),
    ]
