# Generated by Django 4.1.7 on 2023-03-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_tech_carbon_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='fuel_cost',
            field=models.FloatField(),
        ),
    ]
