# Generated by Django 4.1.7 on 2023-03-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_tech_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='default_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
