# Generated by Django 4.2.4 on 2023-10-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_demand_cf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand_cf',
            name='cf_pv',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='demand_cf',
            name='cf_wind',
            field=models.FloatField(),
        ),
    ]
