# Generated by Django 4.2.4 on 2023-10-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_demand_cf_cf_pv_alter_demand_cf_cf_wind'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand_cf',
            name='key',
            field=models.CharField(default='game_variables', max_length=30, unique=True),
        ),
    ]
