# Generated by Django 4.2.4 on 2023-10-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_demand_cf_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='demand_cf',
            constraint=models.UniqueConstraint(fields=('round', 'key'), name='unique_set'),
        ),
    ]
