# Generated by Django 4.2.4 on 2023-11-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_sessions_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand_cf',
            name='cf_pv',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='demand_cf',
            name='cf_wind',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
