# Generated by Django 4.2.4 on 2023-11-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_alter_tech_carbon_content_alter_tech_fuel_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
