# Generated by Django 4.2.4 on 2023-11-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_settings_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
