# Generated by Django 4.2.4 on 2023-11-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
