# Generated by Django 4.2.4 on 2023-11-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_sessions_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
